### ISSUE TITLE
sensors not resetting on change to 'away'

### ISSUE THREAD

**Issue by nickt444** [iainbullock/tesla_ble_mqtt_docker#107]
This is probably a feature request. 
When you disconnect the charger and drive away, it would be good if the sensors reset so they are not reflecting an impossible state.
In my case, the car is 'away' but sensors still say charging at 15A (see image).
I could create a template sensor and automation to reset these sensors when state changes to 'away', but it would be good if this was done natively without having to wait for the car to come back to sync.

![Image](https://github.com/user-attachments/assets/12401efa-4602-444d-bf46-0112db09e4a0)

**Comment by iainbullock** [comment]
As presence is not reliable for everyone (see https://github.com/tesla-local-control/tesla_ble_mqtt_docker/issues/65 ) I'd be relunctant to do this. If we fix presence for everyone then it might be an option for a future release. Thanks for the suggestion!

**Comment by nickt444** [comment]
Circling back on this as it happens pretty regularly. I am using the default to poll every 11 mins. It is very common that I can unplug the car and drive away between poll cycles. State changes to 'away' after ~4 mins, but the above 3 'charger' sensors remain stuck at the value of the last poll before the car was unplugged. Forcing a sync won't work as the car isn't in range, and restarting the container does not reset the sensors. I assume a workaround would be to write an automation to send a MQTT message to reset the sensors based on the state of the presence sensor, but i haven't look at this.
I appreciate the comment about presence not being reliable for everyone, but it seems like this is ignoring a common use case to accommodate an edge case. It is also reflecting a state that can't physically exist. Would it be possible to add this as an off-by-default option and have a switch to enable it (e.g. reset_charge_on_away)? When presence changes from home to away, reset current and power to 0 and charging state to 'disconnected'

**Comment by iainbullock** [comment]
I appreciate the need for your request. I think having this as an option so the user can decide if they want it is a good idea. I will attempt to implement for next release, though now the weather is getting better I spend more time outside so it might take me a while....

I am watching the updates being worked on at https://github.com/teslamotors/vehicle-command to improve bluetooth reliability. If they release something which I think will make a difference, I will dedicate some time to this and include your proposal

**Comment by nickt444** [comment]
Awesome - thanks for considering this. Enjoy the nice weather 🙂
________________________________

**Comment by nickt444** [comment]
As a workaround I am considering an automation that triggers when presence changes from 'home' to 'away'
It looks like each sensor is configured by its own MQTT topic. Would it be sufficient to have HA post the below 3 messages?

tesla_ble/VIN/sensor/charger_power = 0
tesla_ble/VIN/sensor/charger_actual_current = 0
tesla_ble/VIN/sensor/charging_state = Disconnected

**Comment by iainbullock** [comment]
That will work. Here's a screenshot of me testing this in HA Developer tools-> Actions

<img width="838" alt="Image" src="https://github.com/user-attachments/assets/9d80287b-53e5-4c1e-a3a0-f510a4292752" />

**Comment by nickt444** [comment]
here is the automation I used if anyone else is having the same issue:

```
alias: Reset BLE charge state on car away
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.tesla_ble_[VIN]_presence
    to: "off"
conditions: []
actions:
  - if:
      - condition: numeric_state
        entity_id: sensor.tesla_ble_[VIN]_charger_power
        above: 0
    then:
      - action: mqtt.publish
        metadata: {}
        data:
          qos: "0"
          topic: tesla_ble/[VIN]/sensor/charger_power
          payload: "0"
  - if:
      - condition: numeric_state
        entity_id: sensor.tesla_ble_[VIN]_charger_actual_current
        above: 0
    then:
      - action: mqtt.publish
        metadata: {}
        data:
          qos: "0"
          topic: tesla_ble/[VIN]/sensor/charger_actual_current
          payload: "0"
  - if:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.tesla_ble_[VIN]_charging_state
            state: Disconnected
    then:
      - action: mqtt.publish
        metadata: {}
        data:
          qos: "0"
          topic: tesla_ble/[VIN]/sensor/charging_state
          payload: Disconnected
mode: single
```
